import React from 'react';

export default function ReportsPage() {
  return (
    <div className="space-y-6 max-w-5xl mx-auto">
      
      {/* Toolbar */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-6 bg-white p-4 rounded-xl shadow-sm border border-slate-200">
        <div className="mb-4 sm:mb-0">
            <h2 className="text-xl font-bold text-slate-800">Print & Export Center</h2>
            <p className="text-sm text-slate-500">Generate beautiful, printable reports for your clients.</p>
        </div>
        <div className="flex space-x-3 w-full sm:w-auto">
          <button className="flex-1 sm:flex-none px-4 py-2 bg-white border border-slate-300 text-slate-700 font-medium rounded-md shadow-sm hover:bg-slate-50 transition-colors">
            Print View
          </button>
          <button className="flex-1 sm:flex-none px-4 py-2 bg-indigo-600 text-white font-medium rounded-md shadow-sm hover:bg-indigo-700 transition-colors">
            Download PDF
          </button>
        </div>
      </div>

      {/* Print Preview Canvas */}
      <div className="bg-white rounded-xl shadow-lg border border-slate-200 p-10 min-h-[800px] print:shadow-none print:border-none print:p-0">
        <div className="text-center mb-10 pb-6 border-b-2 border-slate-800">
            <h3 className="text-3xl font-bold text-slate-800 uppercase tracking-widest mb-2">Comprehensive Horoscope</h3>
            <p className="text-slate-500">Generated by AstroSaaS Engine</p>
        </div>
        
        <div className="grid grid-cols-2 gap-10 mb-10">
          <div className="bg-slate-50 p-6 rounded-lg border border-slate-100">
            <h4 className="font-bold text-slate-800 mb-3 uppercase tracking-wider text-sm border-b border-slate-200 pb-2">Birth Details</h4>
            <ul className="text-sm space-y-2 text-slate-700">
              <li><span className="font-semibold text-slate-500 w-24 inline-block">Name:</span> John Doe</li>
              <li><span className="font-semibold text-slate-500 w-24 inline-block">Date of Birth:</span> 15 August 1990</li>
              <li><span className="font-semibold text-slate-500 w-24 inline-block">Time of Birth:</span> 14:30:00 (Local)</li>
              <li><span className="font-semibold text-slate-500 w-24 inline-block">Place:</span> New Delhi, India</li>
              <li><span className="font-semibold text-slate-500 w-24 inline-block">Coordinates:</span> 28°36' N, 77°12' E</li>
            </ul>
          </div>
          <div className="bg-slate-50 p-6 rounded-lg border border-slate-100">
            <h4 className="font-bold text-slate-800 mb-3 uppercase tracking-wider text-sm border-b border-slate-200 pb-2">Panchang Elements</h4>
            <ul className="text-sm space-y-2 text-slate-700">
              <li><span className="font-semibold text-slate-500 w-24 inline-block">Tithi:</span> Krishna Ashtami</li>
              <li><span className="font-semibold text-slate-500 w-24 inline-block">Nakshatra:</span> Rohini (Pada 3)</li>
              <li><span className="font-semibold text-slate-500 w-24 inline-block">Yoga:</span> Siddhi</li>
              <li><span className="font-semibold text-slate-500 w-24 inline-block">Karana:</span> Bava</li>
              <li><span className="font-semibold text-slate-500 w-24 inline-block">Sun/Moon:</span> Cancer / Taurus</li>
            </ul>
          </div>
        </div>

        <div className="space-y-6">
          <div className="p-8 border-2 border-dashed border-slate-200 rounded-lg bg-slate-50/50 flex flex-col items-center justify-center text-slate-400">
             <span className="text-lg font-semibold block mb-1">Chart Layout Area</span>
             <span className="text-sm">Main Birth Chart (Lagna) and Navamsha (D9) will be embedded here for printing.</span>
          </div>
          <div className="p-8 border-2 border-dashed border-slate-200 rounded-lg bg-slate-50/50 flex flex-col items-center justify-center text-slate-400">
             <span className="text-lg font-semibold block mb-1">Planetary Table Area</span>
          </div>
        </div>
      </div>
    </div>
  );
}