name: Build Swiss Ephemeris

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Uses your exact compile commands but via native docker to remove warnings
      - name: Build in Amazon Linux 2023
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace amazonlinux:2023 /bin/bash -c "
            dnf -y update && \
            dnf -y install gcc gcc-c++ make && \
            
            cd /workspace/cpp/swisseph && \
            
            gcc -fPIC -O2 -c *.c && \
            gcc -shared -o libswe.so *.o -lm && \
            
            mkdir -p /workspace/apps/web/bin && \
            cp libswe.so /workspace/apps/web/bin/libswe.so
          "

      - name: Commit binary
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add apps/web/bin/libswe.so
          git commit -m "build: amazon linux libswe" || echo "No changes"
          git push
